// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt5GRnZ0etFmEMAAX0hj_mpokZwESwwgE',
    appId: '1:554686005938:web:fd5514b604434fb365ffab',
    messagingSenderId: '554686005938',
    projectId: 'nisa-ticaret',
    authDomain: 'nisa-ticaret.firebaseapp.com',
    storageBucket: 'nisa-ticaret.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZfUPX5bzJB4eyriRWZEXn3Fp4winxMrQ',
    appId: '1:554686005938:android:f82cebebcd2d76a765ffab',
    messagingSenderId: '554686005938',
    projectId: 'nisa-ticaret',
    storageBucket: 'nisa-ticaret.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8c69Q3l2ujYxG72s-gz13RG1mt6nrKuE',
    appId: '1:554686005938:ios:07913650bf9843e965ffab',
    messagingSenderId: '554686005938',
    projectId: 'nisa-ticaret',
    storageBucket: 'nisa-ticaret.firebasestorage.app',
    iosBundleId: 'com.nisaticaret.nisaTicaret',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8c69Q3l2ujYxG72s-gz13RG1mt6nrKuE',
    appId: '1:554686005938:ios:07913650bf9843e965ffab',
    messagingSenderId: '554686005938',
    projectId: 'nisa-ticaret',
    storageBucket: 'nisa-ticaret.firebasestorage.app',
    iosBundleId: 'com.nisaticaret.nisaTicaret',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt5GRnZ0etFmEMAAX0hj_mpokZwESwwgE',
    appId: '1:554686005938:web:6abcca55a0db6aee65ffab',
    messagingSenderId: '554686005938',
    projectId: 'nisa-ticaret',
    authDomain: 'nisa-ticaret.firebaseapp.com',
    storageBucket: 'nisa-ticaret.firebasestorage.app',
  );

}